### ISSUE TITLE
enhancement: add distinct class identifier to modal div.

### ISSUE THREAD

**Issue by jmonroynieto** [o02c/obsidian-tab-navigator#31]
For those of us who like to tinker with CSS to implement visual changes ourselves, it is very valuable to use selectors that easily can be read and recognized to affect a certain element. In the case of the tab navigator modal it's classed generically as "prompt". This is problematic since it could easily clash with another plugin or element. So far it only happens with the default opening note modal. If you could find a way to make the item have both the original "prompt" class and something else ([with a space](https://stackoverflow.com/a/8722176)), we could affect them independently or jointly to our liking) 

My current attempt is rather awkward because it can't differenciate between the open note and tab navigator modals. I use CSS to increase the size of the tab-navigator in relation to my normal text size, I don't mind this right now, but I was trying to do some visual changes that don't jive well with the open note menu.

```
/* obsidian tab-navigator by o02c */
.prompt:has(> .prompt-input-container + .prompt-results) {
   transform: scale(1.4);
    transform-origin: top;
}
```
If there is a way to identify the menu with a class "tabnavigator", or something more interesting Easter egg style like "wayfinder" or "magellan" that would be very much appreciated. 
(see: [plugin setClass method](https://docs.obsidian.md/Reference/TypeScript+API/Setting/setClass))

**Comment by o02c** [comment]
Hi @jmonroynieto 
Sorry for the delay!

I've added a custom class tab-navigator-modal to the modal element, which allows for more specific CSS targeting. Now you can style the tab navigator independently from other modals that use the generic "prompt" class.

Instead of:
```css
.prompt:has(> .prompt-input-container + .prompt-results) {
   transform: scale(1.4);
}
```

You can now use:
```css
.tab-navigator-modal {
   transform: scale(1.4);
}
```

This has been updated in v0.7.3.

**Comment by jmonroynieto** [comment]
I also didn't make the time to test it promptly, please excuse me. This is great, it helps a lot with snippet customization. I just tried my hand at a (hasty) theming option. I'll add the snippet for those interested.
<details><summary>CSS</summary>

```css
.tab-navigator-modal {
   transform: scale(1.2);
   transform-origin: top;
    background-color: #101818;
    .alias {
      color: #D6BA7C;
      font-style: bold;

    }
    .tag:not(:empty) {
    background-color: #2E2921;
    color: #000000;
    border: 3px solid #2E2921;
    border-radius: 6px;
  }
    .is-selected {
      background-color: #9a8a5e ;
      color: #000000;
      .suggestion-title{
      font-weight: 800;
      }
      .tag {
        transform: scale(1.3);
        transform-origin: center;
        box-shadow: 0 0 12px #000000;
      }
      .suggestion-note {
        color: #000000;
        }
      .alias {
        color: #FFFFFF;
        background-color: #101818;
        border: 2px solid #101818;
        border-radius: 6px;
      }
    }
}

```
</details>

![Image](https://github.com/user-attachments/assets/58c1db0a-8313-4439-9a3b-281c30963820)
